sudo: required

language: ruby

services:
  - docker

before_install:
- echo docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t dtulyakov/tzabbix:latest .
- docker run -d dtulyakov/tzabbix:latest
- docker ps -a

script:
- bundle show
